# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        /:title

# Setup
title:            'Yes or No Philosophy'
description:      "An Epistemology Breakthrough"
url:              https://yesornophilosophy.com
baseurl:          /

author:
  name:           'Elliot Temple'
  url:            http://curi.us

paginate:         1

# Custom vars
version:          1.0.0
body-css-id:      "yesno"
ga-id:            "UA-743670-16"

github:
  repo:           https://github.com/curi/websites
  branch:         yesornophilosophy

plugins: [jekyll-paginate]

compress_html:
  comments: ["<!--", "-->"]

# defaults:
#   -
#     scope:
#       path: "docs" # an empty string here means all files in the project
#     values:
#       permalink: /:path:output_ext/
#       