# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        /:title

# Setup
title:            'Rand Quotes'
description:      "by Elliot Temple"
url:              https://randquotes.com
baseurl:          /

author:
  name:           'Elliot Temple'
  url:            https://elliottemple.com

paginate:         1

# Custom vars
version:          1.0.0
body-css-id:      "test"
ga-id:            "UA-743670-1"

github:
  repo:           https://github.com/curi/websites
  branch:         randquotes

plugins: [jekyll-paginate]

compress_html:
  comments: ["<!--", "-->"]

# defaults:
#   -
#     scope:
#       path: "docs" # an empty string here means all files in the project
#     values:
#       permalink: /:path:output_ext/
#       