# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        /:title

# Setup
title:            'Philosophy'
description:      "by Elliot Temple"
url:              https://fallibleideas.com
baseurl:          /

author:
  name:           'Elliot Temple'
  url:            http://curi.us

paginate:         1

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/curi/websites
  branch:         master

plugins: [jekyll-paginate]

compress_html:
  comments: ["<!--", "-->"]

# defaults:
#   -
#     scope:
#       path: "docs" # an empty string here means all files in the project
#     values:
#       permalink: /:path:output_ext/
#       