# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        /:title

# Setup
title:            'Elliot Temple'
description:      "Philosopher"
url:              https://elliottemple.com
baseurl:          /

author:
  name:           'Elliot Temple'
  url:            https://curi.us

paginate:         1

# Custom vars
version:          1.0.0
body-css-id:      "elliottemple"
ga-id:            "UA-743670-4"


github:
  repo:           https://github.com/curi/websites
  branch:         elliottemple

plugins: [jekyll-paginate]

compress_html:
  comments: ["<!--", "-->"]

# defaults:
#   -
#     scope:
#       path: "docs" # an empty string here means all files in the project
#     values:
#       permalink: /:path:output_ext/
#       